# Generated by Django 5.0.6 on 2024-08-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
