# Generated by Django 5.0.6 on 2024-08-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0003_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.department')),
            ],
        ),
    ]
