# Generated by Django 5.0.6 on 2024-09-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Subjectid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
