# Generated by Django 5.0.6 on 2024-09-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0007_remove_teacher_subjectid_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('User_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.subject')),
            ],
        ),
    ]
