# Generated by Django 5.0.6 on 2024-09-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0008_login_tb_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Register_number', models.CharField(max_length=20)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=20)),
                ('Semester', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.login_tb')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
