# Generated by Django 5.0.6 on 2024-09-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0012_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
