# Generated by Django 5.0.6 on 2024-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0013_delete_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hall_no', models.CharField(max_length=20)),
                ('Rows', models.PositiveIntegerField()),
                ('Columns', models.PositiveIntegerField()),
            ],
        ),
    ]
