# Generated by Django 5.0.6 on 2024-09-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0014_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='Columns',
            new_name='Capacity',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='Rows',
        ),
    ]
