# Generated by Django 5.1 on 2024-09-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0015_rename_columns_hall_capacity_remove_hall_rows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
