# Generated by Django 5.1 on 2024-09-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0017_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='departmentid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Loginid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Subjectid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Loginid',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
