# Generated by Django 5.1 on 2024-09-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0019_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.course')),
            ],
        ),
    ]
