# Generated by Django 5.1 on 2024-09-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0020_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.login_tb')),
                ('Subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site_admin.subject')),
            ],
        ),
    ]
