# Generated by Django 5.1 on 2024-09-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0022_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
