# Generated by Django 5.0.6 on 2024-10-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0026_admin_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seating_arrangement',
            name='examid',
        ),
        migrations.RemoveField(
            model_name='seating_arrangement',
            name='hallid',
        ),
        migrations.RemoveField(
            model_name='seating_arrangement',
            name='studentid',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Seating_Arrangement',
        ),
    ]
