# Generated by Django 5.0.6 on 2024-10-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0027_remove_seating_arrangement_examid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_exam', models.DateField()),
            ],
        ),
    ]
