# Generated by Django 5.0.6 on 2024-10-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_admin', '0032_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
